//! The protocol's closed and open vocabularies (IDL §5, plus the enums the IDL
//! declares beside the declaration that uses them).
//!
//! Every enum here is generated by [`protocol_enum!`](crate::protocol_enum), which
//! emits the Rust enum, its wire tokens, and the [`EnumSpec`] the conformance test
//! compares against the IDL. The two cannot disagree: they are one declaration.
//!
//! Closed enums decode fail-closed ([`ProtocolEnum::from_wire`] returns
//! [`UnknownMember`]); `@open` enums are decoded through [`Open`], which surfaces an
//! unrecognized token verbatim and never infers semantics from it
//! (`rule versioning.enums`).
//!
//! [`EnumSpec`]: crate::protocol::spec::EnumSpec
//! [`ProtocolEnum::from_wire`]: crate::protocol::spec::ProtocolEnum::from_wire
//! [`UnknownMember`]: crate::protocol::spec::UnknownMember
//! [`Open`]: crate::protocol::spec::Open

use crate::protocol_enum;

protocol_enum! {
    /// The five authority levels, ordered `read < propose < execute <
    /// revise-intent < promote` (RFC 0027). Agent-facing installations MUST
    /// omit `promote` and `revise_intent` by default.
    closed enum AuthorityLevel {
        /// Wire token `read`.
        read => Read,
        /// Wire token `propose`.
        propose => Propose,
        /// Wire token `execute`.
        execute => Execute,
        /// Wire token `revise-intent`.
        revise_intent = "revise-intent" => ReviseIntent,
        /// Wire token `promote`.
        promote => Promote,
    }
}

protocol_enum! {
    /// Wire encoding of a connection. One encoding per connection,
    /// negotiated at open; canonical field order is identical in both.
    closed enum Encoding {
        /// Canonical JSON (ADR-0013 canonical form), for debugging.
        canonical_json => CanonicalJson,
        /// CBOR with the same canonical field order, for performance.
        canonical_cbor => CanonicalCbor,
    }
}

protocol_enum! {
    /// Result-envelope status (RFC 0026, "Result envelope").
    closed enum ResultStatus {
        /// The operation completed; `verdict` carries its typed outcome.
        ok => Ok,
        /// The operation failed; `error` is present and `verdict` is null.
        error => Error,
        /// A long operation was started; `task` is present.
        task_started => TaskStarted,
        /// A long operation suspended; `task` and `continuation` are present.
        task_suspended => TaskSuspended,
    }
}

protocol_enum! {
    /// Task lifecycle states (plan §4.1;
    /// `schemas/verification-task.schema.json`).
    closed enum TaskStatus {
        /// Wire token `created`.
        created => Created,
        /// Wire token `running`.
        running => Running,
        /// Wire token `suspended`.
        suspended => Suspended,
        /// Wire token `completed`.
        completed => Completed,
        /// Wire token `failed`.
        failed => Failed,
        /// Wire token `cancelled`.
        cancelled => Cancelled,
    }
}

protocol_enum! {
    /// Claim-level verdict vocabulary
    /// (`schemas/assurance-result.schema.json`). Budget exhaustion is never
    /// a verdict; `Unsupported` and engine errors are not verdicts either —
    /// they are `inconclusive` with a typed reason (INV-008).
    closed enum SemanticVerdict {
        /// Wire token `established`.
        established => Established,
        /// Wire token `refuted`.
        refuted => Refuted,
        /// Wire token `inconclusive`.
        inconclusive => Inconclusive,
    }
}

protocol_enum! {
    /// Evaluation-outcome vocabulary of a Context Pack
    /// (`schemas/context-pack.schema.json`).
    closed enum EvaluationVerdict {
        /// Wire token `satisfied`.
        satisfied => Satisfied,
        /// Wire token `refuted`.
        refuted => Refuted,
        /// Wire token `deadlock`.
        deadlock => Deadlock,
        /// Wire token `inconclusive`.
        inconclusive => Inconclusive,
    }
}

protocol_enum! {
    /// Typed `Inconclusive` reason required by INV-008 wherever a verdict is
    /// `inconclusive` (`schemas/assurance-result.schema.json`).
    closed enum InconclusiveReason {
        /// Wire token `Unsupported`.
        Unsupported => Unsupported,
        /// Wire token `ResourceExhausted`.
        ResourceExhausted => ResourceExhausted,
        /// Wire token `EngineError`.
        EngineError => EngineError,
        /// Wire token `InsufficientTelemetry`.
        InsufficientTelemetry => InsufficientTelemetry,
        /// Wire token `AbstractionAmbiguity`.
        AbstractionAmbiguity => AbstractionAmbiguity,
        /// Wire token `IncompleteProofSearch`.
        IncompleteProofSearch => IncompleteProofSearch,
    }
}

protocol_enum! {
    /// Evidence-graph status lattice (plan §11.4, RFC 0038). There is no
    /// `draft` status. Promotion into `validated` or `proved` is
    /// service-restricted; agent votes and confidence never change status.
    closed enum EvidenceStatus {
        /// Wire token `proposed`.
        proposed => Proposed,
        /// Wire token `observed`.
        observed => Observed,
        /// Wire token `sampled`.
        sampled => Sampled,
        /// Wire token `bounded`.
        bounded => Bounded,
        /// Wire token `validated`.
        validated => Validated,
        /// Wire token `proved`.
        proved => Proved,
        /// Wire token `refuted`.
        refuted => Refuted,
        /// Wire token `inconclusive`.
        inconclusive => Inconclusive,
        /// Wire token `superseded`.
        superseded => Superseded,
    }
}

protocol_enum! {
    /// Assurance class of a result (`schemas/context-pack.schema.json`).
    closed enum AssuranceClass {
        /// Wire token `observed`.
        observed => Observed,
        /// Wire token `sampled`.
        sampled => Sampled,
        /// Wire token `bounded`.
        bounded => Bounded,
        /// Wire token `validated`.
        validated => Validated,
        /// Wire token `proved`.
        proved => Proved,
    }
}

protocol_enum! {
    /// Evidence kinds (`schemas/assurance-result.schema.json`).
    closed enum EvidenceKind {
        /// Wire token `example`.
        example => Example,
        /// Wire token `sampled`.
        sampled => Sampled,
        /// Wire token `bounded-schedules`.
        bounded_schedules = "bounded-schedules" => BoundedSchedules,
        /// Wire token `dpor-complete`.
        dpor_complete = "dpor-complete" => DporComplete,
        /// Wire token `finite-exact`.
        finite_exact = "finite-exact" => FiniteExact,
        /// Wire token `symbolic-bounded`.
        symbolic_bounded = "symbolic-bounded" => SymbolicBounded,
        /// Wire token `inductive`.
        inductive => Inductive,
        /// Wire token `parameterized`.
        parameterized => Parameterized,
        /// Wire token `liveness-proof`.
        liveness_proof = "liveness-proof" => LivenessProof,
        /// Wire token `refinement-proof`.
        refinement_proof = "refinement-proof" => RefinementProof,
        /// Wire token `production-observation`.
        production_observation = "production-observation" => ProductionObservation,
        /// Wire token `differential`.
        differential => Differential,
        /// Wire token `certificate`.
        certificate => Certificate,
    }
}

protocol_enum! {
    /// Evidence-graph node kinds (`schemas/evidence-graph-node.schema.json`).
    closed enum EvidenceNodeKind {
        /// Wire token `intent_claim`.
        intent_claim => IntentClaim,
        /// Wire token `assumption`.
        assumption => Assumption,
        /// Wire token `property`.
        property => Property,
        /// Wire token `model`.
        model => Model,
        /// Wire token `program`.
        program => Program,
        /// Wire token `proof_goal`.
        proof_goal => ProofGoal,
        /// Wire token `candidate`.
        candidate => Candidate,
        /// Wire token `invariant_candidate`.
        invariant_candidate => InvariantCandidate,
        /// Wire token `ranking_candidate`.
        ranking_candidate => RankingCandidate,
        /// Wire token `abstraction_map`.
        abstraction_map => AbstractionMap,
        /// Wire token `counterexample`.
        counterexample => Counterexample,
        /// Wire token `explanation`.
        explanation => Explanation,
        /// Wire token `repair_hypothesis`.
        repair_hypothesis => RepairHypothesis,
        /// Wire token `patch`.
        patch => Patch,
        /// Wire token `run`.
        run => Run,
        /// Wire token `certificate`.
        certificate => Certificate,
        /// Wire token `receipt`.
        receipt => Receipt,
        /// Wire token `benchmark_result`.
        benchmark_result => BenchmarkResult,
        /// Wire token `conflict`.
        conflict => Conflict,
        /// Wire token `decision`.
        decision => Decision,
    }
}

protocol_enum! {
    /// The 13 evidence-graph edge types (plan §11.3,
    /// `schemas/evidence-graph-edge.schema.json`).
    closed enum EvidenceEdgeKind {
        /// Wire token `SUPPORTS`.
        SUPPORTS => Supports,
        /// Wire token `REFUTES`.
        REFUTES => Refutes,
        /// Wire token `DEPENDS_ON`.
        DEPENDS_ON => DependsOn,
        /// Wire token `REFINES`.
        REFINES => Refines,
        /// Wire token `EXPLAINS`.
        EXPLAINS => Explains,
        /// Wire token `REPAIRS`.
        REPAIRS => Repairs,
        /// Wire token `INVALIDATES`.
        INVALIDATES => Invalidates,
        /// Wire token `GENERALIZES`.
        GENERALIZES => Generalizes,
        /// Wire token `COUNTEREXAMPLE_TO`.
        COUNTEREXAMPLE_TO => CounterexampleTo,
        /// Wire token `CHECKED_BY`.
        CHECKED_BY => CheckedBy,
        /// Wire token `DERIVED_FROM`.
        DERIVED_FROM => DerivedFrom,
        /// Wire token `CONFLICTS_WITH`.
        CONFLICTS_WITH => ConflictsWith,
        /// Wire token `SUPERSEDES`.
        SUPERSEDES => Supersedes,
    }
}

protocol_enum! {
    /// Semantic fragment (`schemas/intent-contract.schema.json`).
    closed enum Fragment {
        /// Wire token `Finite`.
        Finite => Finite,
        /// Wire token `Symbolic`.
        Symbolic => Symbolic,
        /// Wire token `Temporal`.
        Temporal => Temporal,
        /// Wire token `Probabilistic`.
        Probabilistic => Probabilistic,
        /// Wire token `Theorem`.
        Theorem => Theorem,
        /// Wire token `Runtime`.
        Runtime => Runtime,
    }
}

protocol_enum! {
    /// Policy decision of a diff or gate evaluation
    /// (`schemas/semantic-diff.schema.json`).
    closed enum PolicyDecision {
        /// Wire token `allow`.
        allow => Allow,
        /// Wire token `review`.
        review => Review,
        /// Wire token `block`.
        block => Block,
    }
}

protocol_enum! {
    /// Omission reason (INV-007; `schemas/context-pack.schema.json`).
    closed enum OmissionReason {
        /// Wire token `budget`.
        budget => Budget,
        /// Wire token `redaction`.
        redaction => Redaction,
        /// Wire token `unsupported`.
        unsupported => Unsupported,
        /// Wire token `heuristic-cutoff`.
        heuristic_cutoff = "heuristic-cutoff" => HeuristicCutoff,
        /// Wire token `slice-irrelevant`.
        slice_irrelevant = "slice-irrelevant" => SliceIrrelevant,
    }
}

protocol_enum! {
    /// Reason a value was redacted (plan §4.5;
    /// `schemas/redacted.schema.json`).
    closed enum RedactionReason {
        /// Wire token `summarized`.
        summarized => Summarized,
        /// Wire token `lost`.
        lost => Lost,
        /// Wire token `purged`.
        purged => Purged,
    }
}

protocol_enum! {
    /// Typed per-artifact-class compatibility statement published by every
    /// epoch advance (plan §4.6).
    closed enum Compatibility {
        /// Wire token `Preserved`.
        Preserved => Preserved,
        /// Wire token `Revalidate`.
        Revalidate => Revalidate,
        /// Wire token `Incompatible`.
        Incompatible => Incompatible,
    }
}

protocol_enum! {
    /// Scheduling priority class of a task
    /// (`schemas/verification-task.schema.json`).
    closed enum PriorityClass {
        /// Wire token `interactive`.
        interactive => Interactive,
        /// Wire token `ci`.
        ci => Ci,
        /// Wire token `background`.
        background => Background,
    }
}

protocol_enum! {
    /// Intended reader of a result's context payload. Advisory for
    /// selection and rendering; it never changes a verdict, never widens
    /// authority, and never suppresses an omission or an uncertainty
    /// (RFC 0027 Safety).
    closed enum Audience {
        /// Wire token `agent`.
        agent => Agent,
        /// Wire token `human`.
        human => Human,
        /// Wire token `ci`.
        ci => Ci,
    }
}

protocol_enum! {
    /// Verification portfolio profile (docs/55 sketch, normative here).
    closed enum Portfolio {
        /// Wire token `interactive`.
        interactive => Interactive,
        /// Wire token `promotion`.
        promotion => Promotion,
        /// Wire token `custom`.
        custom => Custom,
    }
}

protocol_enum! {
    /// The 12 repair gates, in order
    /// (`schemas/repair-transaction.schema.json`, plan §8.2).
    closed enum GateName {
        /// Wire token `base_replay`.
        base_replay => BaseReplay,
        /// Wire token `patch_application`.
        patch_application => PatchApplication,
        /// Wire token `intent_integrity`.
        intent_integrity => IntentIntegrity,
        /// Wire token `exact_regression`.
        exact_regression => ExactRegression,
        /// Wire token `neighborhood`.
        neighborhood => Neighborhood,
        /// Wire token `property_mutation`.
        property_mutation => PropertyMutation,
        /// Wire token `defect_mutants`.
        defect_mutants => DefectMutants,
        /// Wire token `refinement_coverage`.
        refinement_coverage => RefinementCoverage,
        /// Wire token `certificate_rebuild`.
        certificate_rebuild => CertificateRebuild,
        /// Wire token `incremental_parity`.
        incremental_parity => IncrementalParity,
        /// Wire token `code_and_security`.
        code_and_security => CodeAndSecurity,
        /// Wire token `receipt_generation`.
        receipt_generation => ReceiptGeneration,
    }
}

protocol_enum! {
    /// Gate outcome (`schemas/repair-transaction.schema.json`).
    closed enum GateStatus {
        /// Wire token `passed`.
        passed => Passed,
        /// Wire token `failed`.
        failed => Failed,
        /// Wire token `pending`.
        pending => Pending,
        /// Wire token `inconclusive`.
        inconclusive => Inconclusive,
        /// Wire token `not_yet_enforced`.
        not_yet_enforced => NotYetEnforced,
    }
}

protocol_enum! {
    /// Expansion relation vocabulary (RFC 0027 "Context policy").
    closed enum ExpansionRelation {
        /// Wire token `causal_predecessors`.
        causal_predecessors => CausalPredecessors,
        /// Wire token `causal_successors`.
        causal_successors => CausalSuccessors,
        /// Wire token `conflicts_with`.
        conflicts_with => ConflictsWith,
        /// Wire token `same_owner`.
        same_owner => SameOwner,
        /// Wire token `property_automaton_step`.
        property_automaton_step => PropertyAutomatonStep,
        /// Wire token `proof_dependency`.
        proof_dependency => ProofDependency,
        /// Wire token `source_span`.
        source_span => SourceSpan,
        /// Wire token `assumption_uses`.
        assumption_uses => AssumptionUses,
        /// Wire token `abstraction_of`.
        abstraction_of => AbstractionOf,
        /// Wire token `refinement_of`.
        refinement_of => RefinementOf,
        /// Wire token `alternate_branch`.
        alternate_branch => AlternateBranch,
    }
}

protocol_enum! {
    /// What an operation is aimed at.
    open enum TargetKind {
        /// Wire token `property`.
        property => Property,
        /// Wire token `claim`.
        claim => Claim,
        /// Wire token `obligation`.
        obligation => Obligation,
        /// Wire token `refinement`.
        refinement => Refinement,
        /// Wire token `module`.
        module => Module,
        /// Wire token `program`.
        program => Program,
        /// Wire token `benchmark_task`. `Target.id` carries a benchmark
        /// task name (`rule benchmark.task_identity`).
        benchmark_task => BenchmarkTask,
        /// Wire token `all_claims`.
        all_claims => AllClaims,
    }
}

protocol_enum! {
    /// Severity of a structural diagnostic.
    closed enum DiagnosticSeverity {
        /// Wire token `error`.
        error => Error,
        /// Wire token `warning`.
        warning => Warning,
        /// Wire token `note`.
        note => Note,
    }
}

protocol_enum! {
    /// The stable error codes of plan §10.3.
    ///
    /// `@open` per `rule versioning.error_codes`: a client MUST treat an
    /// unrecognized code as a non-retryable typed failure.
    open enum ErrorCode {
        /// The named snapshot is not the current one, or is not sealed where
        /// sealing is required.
        StaleSnapshot => StaleSnapshot,
        /// The request needs a semantic feature this daemon does not
        /// implement. Registered-but-unshipped operations use this code.
        UnsupportedSemanticFeature => UnsupportedSemanticFeature,
        /// A protected Intent Contract field was mutated without the
        /// `revise-intent` capability, or against an intent lock (plan §5.4).
        IntentMutationDenied => IntentMutationDenied,
        /// The evidence present does not meet the required assurance class.
        InsufficientEvidence => InsufficientEvidence,
        /// Task budget was exhausted. Never a semantic verdict (docs/49); it
        /// carries the continuation when one exists, or a typed
        /// `non_resumable_reason`.
        BudgetExhausted => BudgetExhausted,
        /// A continuation's pinned engine or semantic epoch does not match the
        /// daemon's current epochs. The daemon MUST NOT silently re-run.
        ContinuationEpochMismatch => ContinuationEpochMismatch,
        /// A source construct maps to more than one semantic element and the
        /// correspondence cannot be decided (plan §16).
        AmbiguousCorrespondence => AmbiguousCorrespondence,
        /// The request crosses a trust boundary the Intent Contract does not
        /// authorize (plan §18).
        UntrustedDomainBoundary => UntrustedDomainBoundary,
        /// An independent checker rejected a certificate or proof artifact.
        CertificateRejected => CertificateRejected,
        /// A replay diverged from the recorded execution.
        ReplayDiverged => ReplayDiverged,
        /// The presented capability's level or scope does not permit the
        /// operation. Checked before any semantic work runs (RFC 0027).
        CapabilityDenied => CapabilityDenied,
        /// A promotion gate or intent policy blocked the operation.
        PolicyGateFailed => PolicyGateFailed,
        /// An intent bundle's acceptance signature chain failed verification,
        /// or the referenced bundle is absent. CI fails closed on this code
        /// (plan §4.2.1, RFC 0037).
        AcceptanceChainInvalid => AcceptanceChainInvalid,
        /// An evidence-graph status promotion lost its compare-and-set against
        /// the claim's current status (plan §11.7, RFC 0038). Re-read and
        /// retry; the lattice never regresses.
        StatusConflict => StatusConflict,
        /// A capability's concurrency or resource quota is exhausted (plan
        /// §4.5). Distinct from `BudgetExhausted`, which is task-budget spend
        /// and carries a continuation.
        QuotaExhausted => QuotaExhausted,
        /// An artifact or continuation declares a schema or semantic epoch
        /// unknown or incompatible with this daemon. Typed rejection, never
        /// best-effort decoding (docs/09 T13).
        EpochUnsupported => EpochUnsupported,
        /// An atomic publication aborted (e.g. disk exhaustion, plan §4.5).
        /// Atomicity is per artifact (INV-017, RFC 0038): the artifact whose
        /// publication aborted is not published, and nothing is truncated. A
        /// composite publication (`workspace.create` or
        /// `workspace.create_by_reference` with `seal`, `workspace.seal`) MAY
        /// leave earlier records published, each complete and receipted, and
        /// never leaves its root published (RFC 0026 "Atomicity of
        /// publication", correction 48).
        PublicationAborted => PublicationAborted,
        /// No protocol version is common to client and daemon, or the client's
        /// major falls outside the N / N−1 window.
        ProtocolVersionUnsupported => ProtocolVersionUnsupported,
        /// The same `idempotency_key` was replayed with a different canonical
        /// request.
        IdempotencyKeyReused => IdempotencyKeyReused,
        /// The request does not parse, does not validate against this file, or
        /// uses an unknown closed-enum member.
        MalformedRequest => MalformedRequest,
    }
}

protocol_enum! {
    /// What a structural operation did. Not the RFC 0031 diff relation vocabulary:
    /// `unchanged` appears in both and means different things in each, and a daemon
    /// MUST NOT derive one from the other (RFC 0026, "Verdicts").
    closed enum StructuralOutcome {
        /// Wire token `created`.
        created => Created,
        /// Wire token `updated`.
        updated => Updated,
        /// Wire token `sealed`.
        sealed => Sealed,
        /// Wire token `accepted`.
        accepted => Accepted,
        /// Wire token `rejected`.
        rejected => Rejected,
        /// Wire token `locked`.
        locked => Locked,
        /// Wire token `cancelled`.
        cancelled => Cancelled,
        /// Wire token `unchanged`.
        unchanged => Unchanged,
        /// Wire token `acknowledged`.
        acknowledged => Acknowledged,
    }
}

protocol_enum! {
    /// A grant a capability carries beyond its level and scope, for the
    /// operations that require one in addition to their `authority` clause.
    ///
    /// `@open` per `rule versioning.enums`: a client MUST NOT infer semantics from an
    /// unrecognized member, which for a grant is the fail-closed reading — a grant it
    /// cannot name is a grant it MUST NOT assume it holds. Adding a member is therefore a
    /// compatible change, which is why the one grant the dossier fixes today does not
    /// close the vocabulary against the next one.
    open enum DataGrant {
        /// The production-trace grant `observe.ingest` requires in addition to
        /// `authority execute` (plan §18.2, with the capture-time contract of
        /// plan §18.4; RFC 0027 R-4).
        production_trace => ProductionTrace,
    }
}

protocol_enum! {
    /// Kind of progress event on a task subscription. Events are hints.
    closed enum TaskEventKind {
        /// Wire token `milestone`.
        milestone => Milestone,
        /// Wire token `progress`.
        progress => Progress,
        /// Wire token `status_change`.
        status_change => StatusChange,
        /// Wire token `evidence_committed`.
        evidence_committed => EvidenceCommitted,
    }
}

protocol_enum! {
    /// Kind of committed evidence-graph delta on an evidence subscription.
    closed enum EvidenceEventKind {
        /// Wire token `node_published`.
        node_published => NodePublished,
        /// Wire token `edge_published`.
        edge_published => EdgePublished,
        /// Wire token `status_transition`.
        status_transition => StatusTransition,
        /// Wire token `conflict_materialized`.
        conflict_materialized => ConflictMaterialized,
    }
}

protocol_enum! {
    /// A layer a diff is computed at (RFC 0031).
    closed enum DiffLayer {
        /// Wire token `textual`.
        textual => Textual,
        /// Wire token `structural`.
        structural => Structural,
        /// Wire token `semantic`.
        semantic => Semantic,
        /// Wire token `intent`.
        intent => Intent,
    }
}

protocol_enum! {
    /// A model-exploration strategy.
    open enum ExplorationStrategy {
        /// Wire token `dpor`.
        dpor => Dpor,
        /// Wire token `observer_indexed_dpor`.
        observer_indexed_dpor => ObserverIndexedDpor,
        /// Wire token `random_schedules`.
        random_schedules => RandomSchedules,
        /// Wire token `symbolic_bounded`.
        symbolic_bounded => SymbolicBounded,
        /// Wire token `unfolding`.
        unfolding => Unfolding,
    }
}

protocol_enum! {
    /// Explanation types of RFC 0039 ("Explanation types"), normative here.
    open enum ExplanationLevel {
        /// Wire token `trace`.
        trace => Trace,
        /// Wire token `causal`.
        causal => Causal,
        /// Wire token `contrastive`.
        contrastive => Contrastive,
        /// Wire token `logical`.
        logical => Logical,
        /// Wire token `correction`.
        correction => Correction,
        /// Wire token `instrumentation`.
        instrumentation => Instrumentation,
        /// Wire token `assurance`.
        assurance => Assurance,
    }
}

protocol_enum! {
    /// The gate profile a repair transaction is evaluated against.
    closed enum GateProfile {
        /// Wire token `phase-b`.
        phase_b = "phase-b" => PhaseB,
        /// Wire token `phase-c`.
        phase_c = "phase-c" => PhaseC,
        /// Wire token `phase-d`.
        phase_d = "phase-d" => PhaseD,
        /// Wire token `default`.
        default => Default,
    }
}
