#!/usr/bin/env python3
"""Bind docs/09 T12 ("Dependency/unsafe compromise") to its live enforcement.

Source of truth:

- `notes/plan/docs/09_THREAT_MODEL.md` T12 — six required controls: pinned
  lockfile; dependency allowlist; cargo-vet/advisory scanning; unsafe boundary
  audit; reproducible build metadata; minimal kernel dependencies.

Five of the six controls already have a mechanical enforcer elsewhere in the
tree; the sixth (cargo-vet/advisory scanning) is
`tools/governance/check_dependency_audit.py`, added alongside this file. This
script does not re-implement any of the six controls — every check it runs is
either (a) a direct, narrow read of two files this evidence artifact is
uniquely responsible for citing (the `--locked` gate discipline and the
`overflow-checks` release setting, neither of which carries its own GOV-1 or
KCOV id), or (b) the *actual* self-test and real run of the checker that
already owns a control, invoked exactly as `Justfile`'s `governance`/`covenant`
recipes invoke it. "Citing" a control here means literally re-running its
enforcer, not copying a status string out of a possibly-stale committed
evidence file, so a control that regresses between commits fails here too —
this file's own gate is `evidence`, not `documentation`.

Control -> enforcement point map
---------------------------------

    pinned lockfile
        `Cargo.lock` exists (this file, `cargo-lock-present`);
        every `Justfile` `cargo` invocation but `fmt`/`fmt-check` carries
        `--locked` (this file, `locked-gates`);
        `GOV-1-01` toolchain-pinned (check_code_policy.py).
    dependency allowlist
        `GOV-1-07` dependency-rationale (check_code_policy.py).
    cargo-vet/advisory scanning
        `dependency-audit-posture` (check_dependency_audit.py, added by this
        Bone to close the one control with no prior enforcer).
    unsafe boundary audit
        `GOV-1-02` unsafe-forbidden (check_code_policy.py).
    reproducible build metadata
        `GOV-1-01` toolchain-pinned; the `--locked` gate discipline (as
        above); `[profile.release] overflow-checks = true` (this file,
        `overflow-checks`); `KCOV-09` receipt-conformance
        (check_kernel_covenant.py — kernel receipts name their build/checker
        identity per INV-014).
    minimal kernel dependencies
        `GOV-1-06` no-network-in-checker (check_code_policy.py); `KCOV-06`
        dependency-freedom (check_kernel_covenant.py — the four
        `continuum-kernel-*` crates admit zero dependencies, workspace or
        external); the crate-boundary rules as a whole
        (check_crate_boundaries.py — `certificate-checker-not-search` and
        `kernel-is-synchronous` in particular).

Self-test
---------

`--self-test` proves two things, neither vacuously:

1. This file's own two direct checks (`locked-gates`, `overflow-checks`) each
   catch a real mutation of the live `Justfile`/`Cargo.toml` text, generated by
   a find/replace against an anchor that must match exactly once — if the
   anchor has drifted, the self-test fails loudly instead of silently testing
   nothing (the same discipline `check_code_policy.py`'s `substitute` fixtures
   use).
2. Every delegate checker's own `--self-test` still exits 0 — i.e., every
   fixture that checker owns is still caught. This file does not carry copies
   of `check_code_policy.py`'s 56 fixtures or `check_kernel_covenant.py`'s 21;
   it requires them to still pass, live, on every run.

Real run
--------

Re-runs every delegate checker for real (no `--self-test`), reads the specific
requirement ids this binding names out of each one's JSON report, runs the two
direct checks against the live `Justfile`/`Cargo.toml`, and fails if any
control's citations are not unanimously "pass".

Scope and honesty about limits
-------------------------------

- "Pinned lockfile" is checked at the level of "the file exists and every gate
  refuses to silently re-resolve it" plus the toolchain-pin control. Whether
  `Cargo.lock` is committed to git (as opposed to merely present on disk) is a
  repository-process fact this script does not query (no `git` subprocess);
  every other gate in `just check` already runs from a git checkout where an
  untracked `Cargo.lock` would not survive `git clean`, and `.gitignore` does
  not exclude it (checked by inspection, not by this script).
- "Reproducible build metadata" is a composite citation, not a single rule:
  no one existing id covers "toolchain pin + locked gates + overflow-checks +
  receipt build identity" as one obligation, so this file states the
  composite explicitly rather than inventing a new id for it.

Stdlib only; the only subprocesses run are the delegate checkers themselves
(each already `python3 tools/...` invocations `just check` runs), never a
network client. Exit 0 when every control's citations pass, 1 otherwise.

Usage:

    python3 tools/governance/check_t12_evidence.py --self-test
    python3 tools/governance/check_t12_evidence.py
    python3 tools/governance/check_t12_evidence.py --evidence tools/governance/evidence/t12.json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE = "tools/governance/evidence/t12.json"
THREAT_MODEL = "notes/plan/docs/09_THREAT_MODEL.md"

DELEGATES: dict[str, str] = {
    "check_code_policy": "tools/governance/check_code_policy.py",
    "check_kernel_covenant": "tools/check_kernel_covenant.py",
    "check_crate_boundaries": "tools/check_crate_boundaries.py",
    "check_dependency_audit": "tools/governance/check_dependency_audit.py",
}


# ============================================================================
# Repository view (fixture overlay for this file's own two direct checks)
# ============================================================================


@dataclass
class Tree:
    root: Path
    overlay: dict[str, str] = field(default_factory=dict)
    removed: frozenset[str] = frozenset()

    def with_changes(self, overlay: dict[str, str], removed: tuple[str, ...] = ()) -> "Tree":
        merged = {**self.overlay, **overlay}
        return Tree(self.root, merged, frozenset(self.removed) | frozenset(removed))

    def read_text(self, rel: str) -> str | None:
        if rel in self.removed:
            return None
        if rel in self.overlay:
            return self.overlay[rel]
        path = self.root / rel
        if not path.is_file():
            return None
        return path.read_text(encoding="utf-8")

    def read_toml(self, rel: str) -> dict | None:
        text = self.read_text(rel)
        if text is None:
            return None
        try:
            return tomllib.loads(text)
        except tomllib.TOMLDecodeError:
            return None


# ============================================================================
# This file's own two direct checks
# ============================================================================

CARGO_CMD = re.compile(r"^@?cargo\s+(\S+)")


def rule_cargo_lock_present(tree: Tree) -> list[str]:
    if tree.read_text("Cargo.lock") is None:
        return ["Cargo.lock is missing"]
    return []


def rule_locked_gates(tree: Tree) -> list[str]:
    text = tree.read_text("Justfile")
    if text is None:
        return ["Justfile is missing"]
    violations: list[str] = []
    for lineno, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = CARGO_CMD.match(stripped)
        if not match:
            continue
        verb = match.group(1)
        if verb == "fmt":
            continue
        if "--locked" not in stripped:
            violations.append(f"Justfile:{lineno} invokes `cargo {verb}` with no --locked: {stripped!r}")
    return violations


def rule_overflow_checks(tree: Tree) -> list[str]:
    doc = tree.read_toml("Cargo.toml")
    if doc is None:
        return ["Cargo.toml is missing or is not valid TOML"]
    value = doc.get("profile", {}).get("release", {}).get("overflow-checks")
    if value is not True:
        return [f"Cargo.toml [profile.release] overflow-checks is {value!r}, expected true"]
    return []


def direct_checks(tree: Tree) -> dict[str, list[str]]:
    return {
        "cargo-lock-present": rule_cargo_lock_present(tree),
        "locked-gates": rule_locked_gates(tree),
        "overflow-checks": rule_overflow_checks(tree),
    }


def direct_self_test(tree: Tree) -> dict[str, object]:
    failures: list[str] = []
    baseline = direct_checks(tree)
    dirty_baseline = {k: v for k, v in baseline.items() if v}
    if dirty_baseline:
        failures.append(f"the real repository already violates direct checks {sorted(dirty_baseline)}")

    caught: list[str] = []

    if not rule_cargo_lock_present(tree.with_changes({}, removed=("Cargo.lock",))):
        failures.append("fixture: removing Cargo.lock did not trip cargo-lock-present")
    else:
        caught.append("cargo-lock-present")

    justfile = tree.read_text("Justfile") or ""
    anchor = "cargo test --workspace --locked"
    if justfile.count(anchor) != 1:
        failures.append(f"locked-gates fixture anchor {anchor!r} matches {justfile.count(anchor)} times, expected 1")
    else:
        dirty = justfile.replace(anchor, "cargo test --workspace", 1)
        if not rule_locked_gates(tree.with_changes({"Justfile": dirty})):
            failures.append("fixture: dropping --locked from `test` did not trip locked-gates")
        else:
            caught.append("locked-gates")

    cargo_toml = tree.read_text("Cargo.toml") or ""
    anchor = "overflow-checks = true"
    if cargo_toml.count(anchor) != 1:
        failures.append(f"overflow-checks fixture anchor {anchor!r} matches {cargo_toml.count(anchor)} times, expected 1")
    else:
        dirty = cargo_toml.replace(anchor, "overflow-checks = false", 1)
        if rule_overflow_checks(tree.with_changes({"Cargo.toml": dirty})) == []:
            failures.append("fixture: flipping overflow-checks to false did not trip overflow-checks")
        else:
            caught.append("overflow-checks")

    return {"status": "fail" if failures else "pass", "checks_caught": sorted(caught), "failures": failures}


# ============================================================================
# Delegate checkers — invoked exactly as `Justfile` invokes them
# ============================================================================


def run_delegate(rel: str, *args: str) -> tuple[int, dict | None, str]:
    path = ROOT / rel
    proc = subprocess.run(
        [sys.executable, str(path), *args],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    try:
        data = json.loads(proc.stdout) if proc.stdout.strip() else None
    except json.JSONDecodeError:
        data = None
    return proc.returncode, data, proc.stdout


def delegate_self_test() -> dict[str, object]:
    results: dict[str, object] = {}
    failed: list[str] = []
    for name, rel in sorted(DELEGATES.items()):
        code, data, _ = run_delegate(rel, "--self-test")
        report = data if isinstance(data, dict) else {}
        # check_crate_boundaries.py's self-test reports its verdict under the
        # key `self_test` rather than `status`; every other delegate uses
        # `status` for both its self-test and its real run.
        status = report.get("status", report.get("self_test"))
        ok = code == 0 and status == "pass"
        results[name] = {"exit_code": code, "status": status}
        if not ok:
            failed.append(f"{name} --self-test did not pass cleanly (exit {code}, status {status!r})")
    return {"status": "fail" if failed else "pass", "delegates": results, "failures": failed}


def delegate_real_run() -> dict[str, dict]:
    reports: dict[str, dict] = {}
    for name, rel in sorted(DELEGATES.items()):
        _, data, _ = run_delegate(rel)
        reports[name] = data or {"status": "fail", "note": "delegate produced no parseable JSON report"}
    return reports


def rid_status(report: dict, rid: str) -> str:
    if rid in report.get("passing", ()):
        return "pass"
    if rid in report.get("failing", {}):
        return "fail"
    return "unknown"


# ============================================================================
# The six-control binding
# ============================================================================


@dataclass(frozen=True)
class Citation:
    artifact: str
    enforces: str
    status: str


def build_controls(direct: dict[str, list[str]], reports: dict[str, dict]) -> dict[str, dict]:
    gov1 = reports["check_code_policy"]
    kcov = reports["check_kernel_covenant"]
    boundaries = reports["check_crate_boundaries"]
    dep_audit = reports["check_dependency_audit"]

    def direct_status(check: str) -> str:
        return "fail" if direct.get(check) else "pass"

    controls: dict[str, list[Citation]] = {
        "pinned lockfile": [
            Citation("Cargo.lock", "the lockfile is present", direct_status("cargo-lock-present")),
            Citation("Justfile", "every non-fmt cargo gate carries --locked", direct_status("locked-gates")),
            Citation(
                "tools/governance/check_code_policy.py GOV-1-01",
                "toolchain/edition pinned exactly",
                rid_status(gov1, "GOV-1-01"),
            ),
        ],
        "dependency allowlist": [
            Citation(
                "tools/governance/check_code_policy.py GOV-1-07",
                "every dependency has exactly one rationale + TCB class entry",
                rid_status(gov1, "GOV-1-07"),
            ),
        ],
        "cargo-vet/advisory scanning": [
            Citation(
                "tools/governance/check_dependency_audit.py",
                "every externally-sourced dependency has a version- and checksum-matched vet entry",
                dep_audit.get("status", "unknown"),
            ),
        ],
        "unsafe boundary audit": [
            Citation(
                "tools/governance/check_code_policy.py GOV-1-02",
                "unsafe_code = forbid, workspace-wide, no relaxation",
                rid_status(gov1, "GOV-1-02"),
            ),
        ],
        "reproducible build metadata": [
            Citation(
                "tools/governance/check_code_policy.py GOV-1-01",
                "toolchain identity is an exact, committed pin",
                rid_status(gov1, "GOV-1-01"),
            ),
            Citation("Justfile", "every non-fmt cargo gate carries --locked", direct_status("locked-gates")),
            Citation(
                "Cargo.toml [profile.release]",
                "overflow-checks = true, so debug/release agree on the determinism matrix",
                direct_status("overflow-checks"),
            ),
            Citation(
                "tools/check_kernel_covenant.py KCOV-09",
                "kernel receipts name checker build/epoch identity per INV-014",
                rid_status(kcov, "KCOV-09"),
            ),
        ],
        "minimal kernel dependencies": [
            Citation(
                "tools/governance/check_code_policy.py GOV-1-06",
                "no network-capable crate or dependency in the certificate-checking closure",
                rid_status(gov1, "GOV-1-06"),
            ),
            Citation(
                "tools/check_kernel_covenant.py KCOV-06",
                "the four continuum-kernel-* crates admit zero dependencies",
                rid_status(kcov, "KCOV-06"),
            ),
            Citation(
                "tools/check_crate_boundaries.py",
                "certificate-checker-not-search and kernel-is-synchronous hold",
                boundaries.get("status", "unknown"),
            ),
        ],
    }

    return {
        control: {
            "citations": [c.__dict__ for c in citations],
            "status": "pass" if all(c.status == "pass" for c in citations) else "fail",
        }
        for control, citations in controls.items()
    }


# ============================================================================
# Evidence
# ============================================================================


def build_evidence(controls: dict[str, dict], direct_st: dict, delegate_st: dict) -> dict:
    overall = "pass" if all(c["status"] == "pass" for c in controls.values()) else "fail"
    return {
        "artifact": "continuum.governance.evidence/t12",
        "produced_by": "tools/governance/check_t12_evidence.py",
        "reproduce": f"python3 tools/governance/check_t12_evidence.py --evidence {EVIDENCE}",
        "authority": f"{THREAT_MODEL} T12 (Dependency/unsafe compromise)",
        "determinism": (
            "This file records no timestamp, commit id, or absolute path: it is a function of the "
            "repository contents and the delegate checkers' own outputs alone, so an unchanged tree "
            "reproduces it byte-for-byte. The only subprocesses run are the delegate checkers listed "
            "below, invoked exactly as Justfile invokes them; none makes a network access."
        ),
        "delegates": sorted(DELEGATES.values()),
        "controls": controls,
        "self_test": {
            "direct": direct_st,
            "delegates": delegate_st,
            "status": "pass" if direct_st.get("status") == "pass" and delegate_st.get("status") == "pass" else "fail",
        },
        "boundary": (
            "Composite citation, not a single mechanical rule of this file's own: 'pinned lockfile' and "
            "'reproducible build metadata' each bind more than one existing id plus two narrow direct "
            "checks (locked-gates, overflow-checks) that no other requirement id owns. This file does not "
            "query git for whether Cargo.lock is tracked; see the module docstring."
        ),
        "status": overall,
    }


# ============================================================================
# Entry point
# ============================================================================


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="prove this file's two direct checks and every delegate's self-test all still catch their fixtures",
    )
    parser.add_argument(
        "--evidence",
        nargs="?",
        const=str(ROOT / EVIDENCE),
        default=None,
        metavar="PATH",
        help="run the self-test and the real binding, then write the evidence JSON to PATH",
    )
    parser.add_argument("--quiet", action="store_true", help="print only the status line")
    args = parser.parse_args(argv)

    tree = Tree(ROOT)

    if args.self_test and not args.evidence:
        direct_st = direct_self_test(tree)
        delegate_st = delegate_self_test()
        status = "pass" if direct_st["status"] == "pass" and delegate_st["status"] == "pass" else "fail"
        report = {"status": status, "direct": direct_st, "delegates": delegate_st}
        print(json.dumps(report, indent=2, sort_keys=True))
        return 0 if status == "pass" else 1

    direct_st: dict[str, object] = {"status": "not-run"}
    delegate_st: dict[str, object] = {"status": "not-run"}
    st_ok = True
    if args.evidence:
        direct_st = direct_self_test(tree)
        delegate_st = delegate_self_test()
        st_ok = direct_st["status"] == "pass" and delegate_st["status"] == "pass"

    direct = direct_checks(tree)
    reports = delegate_real_run()
    controls = build_controls(direct, reports)

    if args.evidence:
        evidence = build_evidence(controls, direct_st, delegate_st)
        path = Path(args.evidence)
        if not path.is_absolute():
            path = ROOT / path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    failing_controls = {k: v for k, v in controls.items() if v["status"] != "pass"}
    report = {
        "controls": {k: v["status"] for k, v in sorted(controls.items())},
        "failing_controls": sorted(failing_controls),
        "self_test": {"direct": direct_st.get("status"), "delegates": delegate_st.get("status")},
        "evidence": args.evidence,
        "status": "fail" if (failing_controls or not st_ok) else "pass",
    }
    if args.quiet:
        print(report["status"])
    else:
        print(json.dumps(report, indent=2, sort_keys=True))
    return 1 if (failing_controls or not st_ok) else 0


if __name__ == "__main__":
    raise SystemExit(main())
